# Generated by Django 2.1.2 on 2018-10-09 11:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0002_holidays_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holidays',
            old_name='holiday_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='holidays',
            old_name='author',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='holidays',
            name='hours',
        ),
        migrations.AddField(
            model_name='holidays',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
